### ISSUE TITLE
Save Prophet Model using pickle

### ISSUE THREAD

**Issue by JoeRishon** [manikyabard/Metrics-Anomaly#7]
**You can use pickle to save the Prophet Model after fitting**
Steps - 
* <del>Use pickle to store the prophet model in 01_prophet-ec2.ipynb  
* <del>Load the model again in the same notebook and show it worked.  
* **Any other improvements are allowed.**

Refer to this for more information:
https://facebook.github.io/prophet/docs/additional_topics.html#saving-models

**Comment by RakshithRAcharya** [comment]
Hey, can I work on this
